import { expect, test, request, type Page } from '@playwright/test'
import { login, enterSelectionMode, openTopbarMenu } from './helpers'

const origin = (process.env.E2E_BASE_URL || 'http://127.0.0.1:18080').replace(/\/$/, '')
const root = '00000000-0000-0000-0000-000000000000'
let recoveryCleanup: string[] | undefined
// Cleanup has its own hook timeout, so a failed UI assertion cannot leave the shared test account protected by TOTP.
test.afterEach(async () => {
  if (!recoveryCleanup) return
  const codes = recoveryCleanup
  recoveryCleanup = undefined
  const cleanup = await request.newContext({ baseURL: origin })
  try {
    const password = process.env.E2E_PASSWORD || 'revaro-e2e-password'
    const login = await cleanup.post('/api/auth/login', { headers: { Origin: origin }, data: { username: process.env.E2E_USERNAME || 'admin', password, second_factor: codes[1] } })
    expect(login.ok(), await login.text()).toBeTruthy()
    const disabled = await cleanup.delete('/api/auth/totp', { headers: { Origin: origin }, data: { current_password: password, code: codes[2] } })
    expect(disabled.ok(), await disabled.text()).toBeTruthy()
  } finally { await cleanup.dispose() }
})

async function post(page: Page, path: string, data: unknown) {
  const response = await page.request.post(path, { headers: { Origin: origin }, data })
  expect(response.ok(), await response.text()).toBeTruthy()
  return response.json()
}
async function createDocument(page: Page, name: string, content = 'original', parent_id = root) {
  return post(page, '/api/documents', { name, content, parent_id })
}
async function search(page: Page, name: string) {
  if (!await page.getByLabel('搜索文件名').isVisible()) await page.getByRole('button', { name: '打开搜索', exact: true }).click()
  await page.getByLabel('搜索文件名').fill(name)
  await page.getByLabel('搜索文件名').press('Enter')
  await expect(page.locator('.file-card')).toHaveCount(1)
}

test('continuous scrolling preserves files and selection, with aligned sorting and expandable topbar search', async ({ page }) => {
  test.setTimeout(90_000)
  await login(page)
  const prefix = `scroll-${Date.now().toString(36)}`
  const folder = await post(page, '/api/directories', { name: prefix, parent_id: root })
  for (let i = 0; i < 203; i++) await createDocument(page, `${prefix}-${String(i).padStart(3, '0')}.md`, 'x'.repeat(i + 1), folder.id)
  const elsewhere = await createDocument(page, `${prefix}-outside.md`, 'outside')
  await page.goto(`/f/${folder.id}`)
  await expect(page.locator('.file-card')).toHaveCount(100)
  await expect(page.getByRole('button', { name: '下一页', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '上一页', exact: true })).toHaveCount(0)
  await expect(page.locator('.folder-meta')).toContainText('203 个项目')
  const sorting = page.getByRole('group', { name: '文件排序', exact: true })
  await expect(sorting.getByRole('button')).toHaveCount(2)
  await expect(sorting.locator('select')).toHaveCount(0)
  const fieldToggle = sorting.getByRole('button', { name: '选择排序字段', exact: true })
  const directionToggle = sorting.getByRole('button', { name: '切换排序方向', exact: true })
  const fields = page.getByRole('group', { name: '排序字段', exact: true })
  await expect(fieldToggle).toHaveText('名称')
  await expect(directionToggle).toHaveText('↑')
  const sort = await sorting.boundingBox()
  const menu = await page.getByLabel('更多操作', { exact: true }).boundingBox()
  expect(sort && menu).toBeTruthy()
  await expect(page.locator('.content-head .desktop-create-actions, .content-head .create-menu, .content-head .upload-menu')).toHaveCount(0)
  expect(menu!.height).toBe(44)
  expect(sort!.width).toBeGreaterThanOrEqual(80)
  expect(sort!.width).toBeLessThanOrEqual(110)
  await expect(fieldToggle.locator('svg')).toHaveCount(0)
  const fieldArea = await fieldToggle.boundingBox()
  const fieldText = await fieldToggle.locator('span').boundingBox()
  expect(Math.abs((fieldText!.x - fieldArea!.x) - (fieldArea!.x + fieldArea!.width - fieldText!.x - fieldText!.width))).toBeLessThanOrEqual(1)
  await fieldToggle.click()
  await expect(fields.getByRole('button')).toHaveText(['名称', '大小', '时间'])
  await fields.getByRole('button', { name: '名称', exact: true }).click()
  await expect(directionToggle).toHaveText('↑')
  await expect(fields).toBeHidden()
  const first = page.locator('.file-card').first()
  const firstElement = await first.elementHandle()
  expect(firstElement).not.toBeNull()
  await enterSelectionMode(page)
  await first.press('Space')
  await page.locator('.listing-end').scrollIntoViewIfNeeded()
  await expect(page.locator('.file-card')).toHaveCount(200)
  expect(await firstElement!.evaluate(node => node.isConnected)).toBeTruthy()
  await expect(first).toHaveClass(/selected/)
  await expect(first.locator('strong')).toHaveText(`${prefix}-000.md`)
  await page.locator('.listing-end').scrollIntoViewIfNeeded()
  await expect(page.locator('.file-card')).toHaveCount(203)
  await expect(page.locator('.listing-end')).toContainText('已显示全部 203 个项目')
  await page.evaluate(() => window.scrollTo(0, 0))
  async function assertSort(label: string, field: string, descending: boolean, firstName: string) {
    const response = page.waitForResponse(response => {
      const url = new URL(response.url())
      return url.pathname === '/api/files' && url.searchParams.get('sort') === field
        && url.searchParams.get('descending') === String(descending)
    })
    if (await fieldToggle.textContent() === label) {
      await directionToggle.click()
    } else {
      await fieldToggle.click()
      await expect(fields.getByRole('button')).toHaveText(['名称', '大小', '时间'])
      await fields.getByRole('button', { name: label, exact: true }).click()
    }
    expect((await response).ok()).toBeTruthy()
    await expect(fieldToggle).toHaveText(label)
    await expect(directionToggle).toHaveText(descending ? '↓' : '↑')
    await expect(fields).toBeHidden()
    await expect(page.locator('.file-card')).toHaveCount(100)
    await expect(first.locator('strong')).toHaveText(firstName)
  }
  await assertSort('大小', 'size', false, `${prefix}-000.md`)
  await assertSort('大小', 'size', true, `${prefix}-202.md`)
  await assertSort('名称', 'name', false, `${prefix}-000.md`)
  await assertSort('名称', 'name', true, `${prefix}-202.md`)
  await assertSort('时间', 'updated', true, `${prefix}-202.md`)
  await assertSort('时间', 'updated', false, `${prefix}-000.md`)
  await expect(page.getByLabel('搜索文件名')).toBeHidden()
  const toggle = page.getByRole('button', { name: '打开搜索', exact: true })
  await expect(toggle.locator('svg circle')).toHaveCount(1)
  await expect(page.locator('.search-surface')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  await expect(toggle).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  await toggle.hover()
  await expect(toggle).toHaveCSS('background-color', 'rgb(232, 240, 246)')
  const circle = await page.locator('.search-toggle').boundingBox()
  const neighbors = page.locator('.top-actions .action-menu > summary, .top-actions > .account-button')
  const before = await neighbors.evaluateAll(elements => elements.map(element => element.getBoundingClientRect().toJSON()))
  await toggle.click()
  const input = page.getByLabel('搜索文件名')
  await expect(input).toBeVisible()
  await expect(input).toBeFocused()
  await input.hover()
  await expect(page.locator('.search-toggle')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  expect(await neighbors.evaluateAll(elements => elements.map(element => element.getBoundingClientRect().toJSON()))).toEqual(before)
  const expanded = await page.locator('.search-surface').boundingBox()
  expect(expanded!.x).toBeLessThan(circle!.x)
  expect(Math.abs(expanded!.x + expanded!.width - circle!.x - circle!.width)).toBeLessThanOrEqual(1)
  await expect(page.getByRole('button', { name: '搜索', exact: true })).toHaveCount(0)
  await expect(page.locator('.search-scope, #search-scope-options')).toHaveCount(0)
  await input.fill(`${prefix}-outside`)
  await input.press('Enter')
  await expect(page.locator('.file-card')).toHaveCount(0)
  await page.goto(`/f/${root}`)
  await expect(page.getByRole('navigation', { name: '当前路径', exact: true }).getByRole('button', { name: '我的文件', exact: true })).toBeVisible()
  await page.getByLabel('打开搜索', { exact: true }).click()
  await expect(input).toHaveValue('')
  await input.fill(`${prefix}-outside`)
  await input.press('Enter')
  await expect(page.locator('.file-card')).toHaveCount(1)
  await expect(page.locator('.file-card strong')).toHaveText(elsewhere.name)
  await input.press('Escape')
  await expect(input).toBeHidden()
  await page.locator('.folder-meta').hover()
  await expect(page.locator('.search-surface')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  await expect(page.locator('.search-toggle')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  await expect(page.getByRole('button', { name: '打开搜索', exact: true })).toBeFocused()
  await page.getByRole('button', { name: '打开搜索', exact: true }).click()
  await expect(input).toHaveValue(`${prefix}-outside`)
})

test('scroll loading can retry and ignores a late batch after search changes', async ({ page }) => {
  test.setTimeout(90_000)
  await login(page)
  const prefix = `retry-${Date.now().toString(36)}`
  const folder = await post(page, '/api/directories', { name: prefix, parent_id: root })
  for (let i = 0; i < 103; i++) await createDocument(page, `${prefix}-${String(i).padStart(3, '0')}.md`, 'x', folder.id)
  await page.goto(`/f/${folder.id}`)
  await expect(page.locator('.file-card')).toHaveCount(100)
  const batch = '**/api/files?**offset=100&**'
  await page.route(batch, route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'temporary listing error' }) }))
  await page.locator('.listing-end').scrollIntoViewIfNeeded()
  await expect(page.getByRole('button', { name: '重试加载' })).toBeVisible()
  await expect(page.locator('.file-card')).toHaveCount(100)
  await page.unroute(batch)
  await page.getByRole('button', { name: '重试加载' }).click()
  await expect(page.locator('.file-card')).toHaveCount(103)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.getByRole('button', { name: '切换排序方向', exact: true }).click()
  await expect(page.locator('.file-card')).toHaveCount(100)
  let release!: () => void
  const gate = new Promise<void>(resolve => { release = resolve })
  let fetched!: () => void
  const pending = new Promise<void>(resolve => { fetched = resolve })
  let delivered!: () => void
  const delivery = new Promise<void>(resolve => { delivered = resolve })
  await page.route(batch, async route => {
    const response = await route.fetch()
    fetched()
    await gate
    await route.fulfill({ response })
    delivered()
  })
  await page.locator('.listing-end').scrollIntoViewIfNeeded()
  await pending
  await search(page, `${prefix}-102`)
  const lateResponse = page.waitForResponse(response => response.url().includes('offset=100&'))
  release()
  await delivery
  await (await lateResponse).finished()
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(resolve)))
  await page.unroute(batch)
  await expect(page.locator('.file-card')).toHaveCount(1)
  await expect(page.locator('.file-card strong')).toHaveText(`${prefix}-102.md`)
})

test('mobile search expands left inside the header, preserving other controls and keyboard dismissal', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 720 })
  await login(page)
  const fieldToggle = page.getByRole('button', { name: '选择排序字段', exact: true })
  const fields = page.getByRole('group', { name: '排序字段', exact: true })
  await fieldToggle.click()
  await expect(fields.getByRole('button')).toHaveText(['名称', '大小', '时间'])
  await page.keyboard.press('Escape')
  await expect(fields).toBeHidden()
  await expect(fieldToggle).toBeFocused()
  await fieldToggle.click()
  await page.locator('.breadcrumbs').click({ position: { x: 1, y: 1 } })
  await expect(fields).toBeHidden()
  const circle = await page.locator('.search-toggle').boundingBox()
  const accountBefore = await page.locator('.account-button').boundingBox()
  await page.getByRole('button', { name: '打开搜索', exact: true }).click()
  const input = page.getByLabel('搜索文件名')
  await expect(input).toBeVisible()
  await expect(input).toBeFocused()
  const panel = await page.locator('.search-surface').boundingBox()
  const accountAfter = await page.locator('.account-button').boundingBox()
  expect(accountAfter).toEqual(accountBefore)
  expect(panel!.x).toBeLessThan(circle!.x)
  const header = await page.locator('.topbar').boundingBox()
  expect(panel && header).toBeTruthy()
  expect(panel!.y).toBeGreaterThanOrEqual(header!.y)
  expect(panel!.y + panel!.height).toBeLessThanOrEqual(header!.y + header!.height)
  await expect(page.getByRole('button', { name: '搜索', exact: true })).toHaveCount(0)
  expect(panel!.x).toBeGreaterThanOrEqual(0)
  expect(panel!.x + panel!.width).toBeLessThanOrEqual(320)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(320)
  const sorting = page.getByRole('group', { name: '文件排序', exact: true })
  await expect(sorting.getByRole('button')).toHaveCount(2)
  const sort = await sorting.boundingBox()
  const menu = await page.getByLabel('更多操作', { exact: true }).boundingBox()
  expect(sort && menu).toBeTruthy()
  expect(sort!.width).toBeGreaterThanOrEqual(80)
  expect(sort!.width).toBeLessThanOrEqual(110)
  for (const button of await sorting.getByRole('button').all()) {
    const bounds = await button.boundingBox()
    expect(bounds!.y).toBeGreaterThanOrEqual(sort!.y)
    expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(sort!.y + sort!.height)
    expect(await button.evaluate(element => element.scrollWidth <= element.clientWidth)).toBeTruthy()
  }
  expect(sort!.y).toBeGreaterThan(menu!.y + menu!.height)
  expect(menu!.height).toBe(40)
  expect(menu!.height).toBe(accountBefore!.height)
  await expect(page.locator('.search-scope, #search-scope-options')).toHaveCount(0)
  const close = page.getByRole('button', { name: '收起搜索', exact: true })
  await input.press('Tab')
  await expect(close).toBeFocused()
  expect(await close.evaluate(element => element.matches(':focus-visible'))).toBeTruthy()
  await expect(close).toHaveCSS('outline-style', 'none')
  await expect(close).not.toHaveCSS('box-shadow', 'none')
  await input.click()
  await close.click()
  await expect(input).toBeHidden()
  await expect(page.getByLabel('打开搜索', { exact: true })).toBeFocused()
  await page.getByLabel('打开搜索', { exact: true }).click()
  await expect(input).toBeFocused()
  await input.fill('这是超过输入框长度的文件名称'.repeat(8))
  await expect.poll(async () => (await page.locator('.search-surface').boundingBox())!.width).toBeLessThanOrEqual(200)
  expect(await page.locator('.account-button').boundingBox()).toEqual(accountBefore)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(320)
  await page.keyboard.press('Escape')
  await expect(input).toBeHidden()
  await page.getByLabel('打开搜索', { exact: true }).click()
  await page.locator('.content').click({ position: { x: 3, y: 240 } })
  await expect(input).toBeHidden()
  await page.getByLabel('打开搜索', { exact: true }).click()
  await close.click()
  await expect(input).toBeHidden()
  expect(await page.locator('.account-button').boundingBox()).toEqual(accountBefore)
  await page.locator('.account-button').click()
  await expect(page.locator('.account-modal')).toBeVisible()
})

test('editor saves history, previews an old version and restores its contents', async ({ page }) => {
  await login(page)
  const name = `history-${Date.now().toString(36)}.md`
  const file = await createDocument(page, name)
  await page.reload()
  await search(page, name)
  await page.locator('.file-card').click()
  const editor = page.locator('.document-editor')
  await expect(editor.getByLabel('文档内容')).toHaveValue('original')
  await editor.getByLabel('文档内容').fill('updated content')
  await editor.getByRole('button', { name: '保存', exact: true }).click()
  await expect(editor.getByRole('button', { name: '保存', exact: true })).toBeDisabled()
  await editor.getByRole('button', { name: '版本历史', exact: true }).click()
  const history = editor.getByRole('dialog', { name: '版本历史', exact: true })
  await expect(history.locator('.history-row')).toHaveCount(1)
  await history.getByRole('button', { name: '查看', exact: true }).click()
  await expect(history.locator('pre')).toHaveText('original')
  await history.getByRole('button', { name: '恢复此版本' }).click()
  await expect(editor.getByLabel('文档内容')).toHaveValue('original')
  await expect(history).toBeHidden()
  const content = await page.request.get(`/api/files/${file.id}/content`)
  expect((await content.json()).content).toBe('original')
})

test('expiring share links are visible in the topbar popover and can be revoked', async ({ page }) => {
  await login(page)
  const name = `share-${Date.now().toString(36)}.md`
  await createDocument(page, name)
  await page.reload()
  await search(page, name)
  await enterSelectionMode(page)
  await page.locator('.file-card').press('Space')
  await page.locator('.selection-toolbar').getByRole('button', { name: '分享', exact: true }).click()
  const share = page.getByRole('dialog', { name: '分享文件' })
  await share.getByLabel('分享有效期').selectOption('86400')
  await share.getByRole('button', { name: '创建公开链接' }).click()
  const url = await share.getByLabel('分享链接').inputValue()
  expect((await page.request.get(url)).status()).toBe(200)
  await expect(share).toContainText('当前链接到期时间')
  await share.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(share).toBeHidden()
  await openTopbarMenu(page)
  await page.getByLabel('公开链接', { exact: true }).click()
  const row = page.locator('.public-links-popover .public-link-row').filter({ hasText: name })
  await expect(row).toContainText('有效')
  await row.getByRole('button', { name: '撤销链接' }).click()
  await expect(row).toHaveCount(0)
  expect((await page.request.get(url)).status()).toBe(404)
  await expect(page.locator('.public-links-popover').getByText('暂无公开链接', { exact: true })).toBeVisible()
  await expect(page.locator('.public-links-popover').getByRole('button', { name: '上一页', exact: true })).toHaveCount(0)
  await expect(page.locator('.public-links-popover').getByRole('button', { name: '下一页', exact: true })).toHaveCount(0)
})

test('directory actions offer recursive copy and a downloadable ZIP', async ({ page }) => {
  await login(page)
  const name = `folder-${Date.now().toString(36)}`
  const folder = await post(page, '/api/directories', { name, parent_id: root })
  await createDocument(page, 'nested.md', 'folder data', folder.id)
  await page.reload()
  await search(page, name)
  await enterSelectionMode(page)
  await page.locator('.file-card').press('Space')
  await page.locator('.selection-toolbar').getByRole('button', { name: '复制到', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '复制', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  const response = await page.request.get(`/api/files?parent_id=${root}&q=${name}`)
  const listing = await response.json()
  expect(listing.items).toHaveLength(2)
  await enterSelectionMode(page)
  await page.locator('.file-card').filter({ hasText: name }).first().press('Space')
  const downloadPromise = page.waitForEvent('download')
  await page.locator('.selection-toolbar').getByRole('button', { name: /^下载/ }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('revaro-download.zip')
  expect(await download.failure()).toBeNull()
})

test('refreshing an unfinished multipart upload lets the user reselect and resume the original file', async ({ page }) => {
  await login(page)
  const name = `resume-${Date.now().toString(36)}.bin`
  const size = 17 * 1024 * 1024
  const upload = await post(page, '/api/uploads', { parent_id: root, name, size, mime_type: 'application/octet-stream' })
  const bytes = Buffer.alloc(size, 7)
  const firstPart = await page.request.put(`/api/uploads/${upload.upload_id}/data/1`, { headers: { Origin: origin }, data: bytes.subarray(0, upload.part_size) })
  expect(firstPart.status()).toBe(204)
  await page.request.put(`/api/uploads/${upload.upload_id}/parts/1`, { headers: { Origin: origin }, data: { etag: firstPart.headers().etag, size: upload.part_size } })
  // Only unfinished session metadata is persisted; reselection resumes existing parts.
  await page.evaluate(({ uploadId, name, size, parentId }) => localStorage.setItem('revaro.uploads.v1', JSON.stringify([{ uploadId, parentId, name, size, lastModified: 1700000000000 }])), { uploadId: upload.upload_id, name, size, parentId: root })
  await page.reload()
  await expect(page.getByLabel('选择文件上传', { exact: true })).toHaveCount(1)
  await page.evaluate(({ name, size }) => {
    const input = document.querySelector('input[aria-label="选择文件上传"]') as HTMLInputElement
    const transfer = new DataTransfer()
    transfer.items.add(new File([new Uint8Array(size).fill(7)], name, { type: 'application/octet-stream', lastModified: 1700000000000 }))
    input.files = transfer.files
    input.dispatchEvent(new Event('change', { bubbles: true }))
  }, { name, size })
  await expect.poll(async () => (await (await page.request.get(`/api/uploads/${upload.upload_id}`)).json()).status, { timeout: 20000 }).toBe('completed')
  const file = await page.request.get(`/api/files/${upload.file_id}/download`)
  expect(Buffer.compare(await file.body(), bytes)).toBe(0)
  await expect(page.getByRole('region', { name: '上传进度', exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('revaro.uploads.v1') || '[]'))).toEqual([])
})

test('trash items can be restored and permanently removed from the browser', async ({ page }) => {
  await login(page)
  const name = `trash-${Date.now().toString(36)}.md`
  const file = await createDocument(page, name)
  await page.reload()
  await search(page, name)
  const card = page.locator('.file-card').filter({ hasText: name })
  await enterSelectionMode(page)
  await card.press('Space')
  await page.locator('.selection-toolbar').getByRole('button', { name: /删除/ }).click()
  await page.getByRole('dialog').getByRole('button', { name: /回收站|删除/ }).click()
  await expect(card).toHaveCount(0)
  await page.getByRole('navigation', { name: '主导航', exact: true }).getByRole('link', { name: '回收站', exact: true }).click()
  await expect(card).toHaveCount(1)
  await enterSelectionMode(page)
  await card.press('Space')
  await page.locator('.selection-toolbar').getByRole('button', { name: /恢复/ }).click()
  await expect(card).toHaveCount(0)
  expect((await page.request.get(`/api/files/${file.id}`)).status()).toBe(200)
  await page.request.delete(`/api/files/${file.id}`, { headers: { Origin: origin } })
  await page.getByRole('navigation', { name: '主导航', exact: true }).getByRole('link', { name: '回收站', exact: true }).click()
  await expect(card).toHaveCount(1)
  await enterSelectionMode(page)
  await card.press('Space')
  await page.locator('.selection-toolbar').getByRole('button', { name: /永久删除/ }).click()
  await page.getByRole('dialog').getByRole('button', { name: /永久删除/ }).click()
  await expect(card).toHaveCount(0)
  expect((await page.request.get(`/api/files/${file.id}`)).status()).toBe(404)
})

test('browser login accepts a one-time TOTP recovery code and logout clears reader caches', async ({ page }) => {
  test.setTimeout(90000)
  const { createHmac } = await import('node:crypto')
  await login(page)
  const password = process.env.E2E_PASSWORD || 'revaro-e2e-password'
  const setup = await post(page, '/api/auth/totp/setup', { current_password: password })
  let bits = ''
  for (const char of setup.secret.toUpperCase().replace(/=+$/, '')) bits += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(char).toString(2).padStart(5, '0')
  const key = Buffer.from(bits.match(/.{8}/g)!.map((byte: string) => parseInt(byte, 2)))
  const counter = Buffer.alloc(8)
  counter.writeBigUInt64BE(BigInt(Math.floor(Date.now() / 30000)))
  const digest = createHmac('sha1', key).update(counter).digest()
  const offset = digest[digest.length - 1] & 15
  const code = ((digest.readUInt32BE(offset) & 0x7fffffff) % 1000000).toString().padStart(6, '0')
  const enabled = await post(page, '/api/auth/totp/enable', { current_password: password, code })
  recoveryCleanup = enabled.recovery_codes
  {
    await page.getByRole('button', { name: '打开账户设置', exact: true }).click()
    await page.getByRole('button', { name: '退出登录', exact: true }).click()
    await expect(page.getByLabel('用户名')).toBeVisible()
    await page.getByLabel('用户名').fill(process.env.E2E_USERNAME || 'admin')
    await page.getByLabel('密码', { exact: true }).fill(password)
    await page.getByRole('button', { name: '进入我的内容库' }).click()
    await page.getByLabel('验证码或恢复码').fill(enabled.recovery_codes[0])
    await page.getByRole('button', { name: '进入我的内容库' }).click()
    await page.getByRole('navigation', { name: '主导航', exact: true }).getByRole('link', { name: '文件', exact: true }).click()
    await expect(page.getByRole('navigation', { name: '当前路径', exact: true }).getByRole('button', { name: '我的文件', exact: true })).toBeVisible()
    const status = await (await page.request.get('/api/auth/totp')).json()
    expect(status.recovery_codes).toBe(enabled.recovery_codes.length - 1)
    await page.evaluate(async () => {
      localStorage.setItem('revaro-reader-manifest:test', '{}')
      const cache = await caches.open('revaro-reader-flow-v2')
      await cache.put('/api/files/test/book/flow/chunks/0', new Response('private test data'))
    })
    await page.getByRole('button', { name: '打开账户设置', exact: true }).click()
    await page.getByRole('button', { name: '退出登录', exact: true }).click()
    await expect(page.getByLabel('用户名')).toBeVisible()
    await expect.poll(() => page.evaluate(async () => ({ manifest: localStorage.getItem('revaro-reader-manifest:test'), cache: (await caches.keys()).includes('revaro-reader-flow-v2') }))).toEqual({ manifest: null, cache: false })
  }
})
