import { expect, test, type Locator } from '@playwright/test'
import { mkdirSync } from 'node:fs'
import { login, navigate, pauseMusic, uploadFixture, openMusicPlayer } from './helpers'

function wav() {
  const data = Buffer.alloc(44 + 16000 * 90)
  data.write('RIFF'); data.writeUInt32LE(data.length - 8, 4); data.write('WAVEfmt ', 8)
  data.writeUInt32LE(16, 16); data.writeUInt16LE(1, 20); data.writeUInt16LE(1, 22)
  data.writeUInt32LE(8000, 24); data.writeUInt32LE(16000, 28)
  data.writeUInt16LE(2, 32); data.writeUInt16LE(16, 34)
  data.write('data', 36); data.writeUInt32LE(data.length - 44, 40)
  return data
}

for (const width of [1600, 1024, 900, 850, 390, 320]) {
  test.describe(`floating player at ${width}px`, () => {
    const mobile = width < 1024
    test.use({ viewport: { width, height: 900 }, hasTouch: mobile, reducedMotion: 'no-preference' })

    test('orb, detail panel and ending playback share one persistent audio session', async ({ page }) => {
      test.setTimeout(90_000)
      const activate = (control: Locator) => mobile ? control.tap() : control.click()
      const outsideBlank = () => mobile ? page.touchscreen.tap(width - 4, 120) : page.mouse.click(width - 4, 120)
      const errors: string[] = []
      page.on('pageerror', error => errors.push(error.stack || error.message))
      await login(page)
      // An account-wide session can be restored in a fresh browser context.
      // End it explicitly so this UI fixture starts with an empty player.
      if (await page.locator('.music-orb').count()) {
        await openMusicPlayer(page)
        await page.getByLabel('播放器更多操作', { exact: true }).click()
        await page.getByRole('button', { name: '结束播放', exact: true }).click()
      }
      await expect(page.locator('.music-orb, .music-dock')).toHaveCount(0)
      const headers = { origin: new URL(page.url()).origin }
      const prefix = `floating-player-${Date.now()}`
      const created = await page.request.post('/api/directories', { headers, data: { parent_id: '00000000-0000-0000-0000-000000000000', name: prefix } })
      expect(created.status()).toBe(201)
      const { id } = await created.json()
      let collectionId: string | undefined
      try {
        const files = []
        for (let index = 1; index <= 2; index++) files.push(await uploadFixture(page, id, `${prefix}-${index}.wav`, 'audio/wav', wav()))
        await uploadFixture(page, id, `${files[0].name}.chapters.vtt`, 'text/vtt', Buffer.from('WEBVTT\n\n00:00.000 --> 00:40.000\nIntro\n\n00:40.000 --> 01:30.000\nEnd\n'))
        await uploadFixture(page, id, `${files[0].name}.vtt`, 'text/vtt', Buffer.from('WEBVTT\n\n00:00.000 --> 00:30.000\nPrelude\n\n00:30.000 --> 01:00.000\nChorus\n\n01:00.000 --> 01:30.000\nOutro\n'))
        const collection = await page.request.post('/api/library/collections', { headers, data: { name: prefix, kind: 'audio' } })
        expect(collection.status()).toBe(200)
        collectionId = (await collection.json()).id
        for (const file of files) await page.request.put(`/api/library/collections/${collectionId}/items/${file.id}`, { headers })
        await navigate(page, '音乐')
        await page.getByLabel('选择集合', { exact: true }).click()
        await page.getByRole('button', { name: `${prefix} · 2`, exact: true }).click()
        await page.getByRole('button', { name: `打开 ${files[0].name}`, exact: true }).click()
        const audio = page.locator('audio:not([aria-hidden="true"])')
        const panel = page.locator('.music-dock')
        const orb = page.locator('.music-orb')
        const shell = page.locator('.music-orb-shell')
        const collapse = panel.getByRole('button', { name: '收起播放器', exact: true })
        const firstSource = `/api/files/${files[0].id}/preview`
        await expect(audio).toHaveJSProperty('paused', false)
        await expect(orb).toBeVisible()
        await expect(panel).toBeHidden()
        await expect(panel).toHaveAttribute('inert', '')
        await expect(page.locator('.music-dock-compact, .dock-expand')).toHaveCount(0)
        await expect(shell.locator('button, summary')).toHaveCount(1)
        await expect(shell.locator('.action-menu')).toHaveCount(0)
        const audioCount = await page.locator('audio').count()
        expect((await orb.boundingBox())!.width).toBe(mobile ? 60 : 80)
        expect((await orb.boundingBox())!.height).toBe(mobile ? 60 : 80)
        await expect(orb.locator('.music-orb-cover')).toHaveCSS('border-radius', '50%')
        const ring = orb.locator('.music-orb-progress')
        const initialProgress = Number(await ring.evaluate(element => (element as SVGElement).style.strokeDashoffset))
        await expect.poll(async () => Number(await ring.evaluate(element => (element as SVGElement).style.strokeDashoffset))).toBeLessThan(initialProgress)
        const nav = page.getByRole('navigation', { name: '移动端导航', exact: true })
        const navBounds = width <= 850 ? (await nav.boundingBox())! : undefined
        if (navBounds) expect((await orb.boundingBox())!.y + (await orb.boundingBox())!.height).toBeLessThan(navBounds.y)
        await audio.evaluate((element: HTMLAudioElement) => {
          element.dataset.playerSession = 'original'
          element.dataset.playerEvents = '0'
          for (const type of ['pause', 'play', 'loadstart', 'emptied', 'loadedmetadata']) element.addEventListener(type, () => { element.dataset.playerEvents = String(Number(element.dataset.playerEvents) + 1) })
        })
        await activate(orb)
        await expect(panel).toBeVisible()
        await expect(orb).toBeHidden()
        await expect(collapse).toBeFocused()
        await expect(panel).not.toHaveAttribute('inert', '')
        await expect(panel).toHaveAttribute('aria-hidden', 'false')
        await expect(panel).toHaveCSS('transition-duration', '0.24s, 0.24s, 0s')
        await expect.poll(() => panel.evaluate(element => getComputedStyle(element).opacity)).toBe('1')
        const panelBounds = (await panel.boundingBox())!
        expect(panelBounds.width).toBe(mobile ? width - 24 : 400)
        expect(panelBounds.y).toBeGreaterThanOrEqual(0)
        expect(panelBounds.y + panelBounds.height).toBeLessThan(navBounds?.y ?? 900)
        for (const label of ['上一首', '下一首', '暂停音乐', '音轨章节']) await expect(panel.getByRole('button', { name: label, exact: true })).toBeVisible()
        const volumeTrigger = panel.getByLabel('音乐音量设置', { exact: true })
        const volumeMenu = panel.locator('details:has(> summary[aria-label="音乐音量设置"])')
        const moreTrigger = panel.getByLabel('播放器更多操作', { exact: true })
        const moreMenu = panel.locator('details:has(> summary[aria-label="播放器更多操作"])')
        const slider = panel.getByLabel('音乐音量', { exact: true })
        await expect(volumeTrigger).toBeVisible()
        await expect(slider).toBeHidden()
        await expect(panel.locator('.dock-body > input, .dock-body > .dock-volume')).toHaveCount(0)
        await expect(panel.getByRole('region', { name: '歌词与字幕', exact: true })).toBeVisible()
        const lyricBounds = (await panel.locator('.dock-lyrics').boundingBox())!
        const coverBounds = (await panel.locator('.dock-track').boundingBox())!
        const seekBounds = (await panel.locator('.dock-progress').boundingBox())!
        expect(lyricBounds.y).toBeGreaterThanOrEqual(coverBounds.y + coverBounds.height)
        expect(lyricBounds.y + lyricBounds.height).toBeLessThanOrEqual(seekBounds.y)
        const mode = panel.locator('.playback-mode')
        await activate(mode.getByLabel('播放模式', { exact: true }))
        await expect(mode.locator('.action-menu-panel > button')).toHaveText(['顺序播放', '随机播放', '列表循环', '单曲循环'])
        await mode.getByRole('button', { name: '列表循环', exact: true }).click()
        await expect(panel).toBeVisible()
        await expect(mode.locator('details')).not.toHaveAttribute('open', '')
        await activate(volumeTrigger)
        await expect(slider).toBeVisible()
        await slider.press('Home')
        for (let step = 0; step < 7; step++) await slider.press('ArrowRight')
        await expect(panel.getByLabel('当前音乐音量', { exact: true })).toHaveText('35%')
        await panel.getByLabel('当前音乐音量', { exact: true }).click()
        await expect(volumeMenu).toHaveAttribute('open', '')
        await slider.press('ArrowRight')
        await expect(volumeMenu).toHaveAttribute('open', '')
        await slider.press('ArrowLeft')
        await slider.press('Escape')
        await expect(slider).toBeHidden()
        await expect(volumeTrigger).toBeFocused()
        await expect(panel).toBeVisible()
        await activate(volumeTrigger)
        await panel.locator('.dock-lyrics').click()
        await expect(slider).toBeHidden()
        await activate(volumeTrigger)
        // Opening another native disclosure also dismisses the current menu.
        await moreMenu.evaluate((details: HTMLDetailsElement) => { details.open = true })
        await expect(moreMenu).toHaveAttribute('open', '')
        await expect(slider).toBeHidden()
        await expect(page.locator('.action-menu[open]:not(.embedded-menu)')).toHaveCount(1)
        await moreTrigger.press('Escape')
        await expect(moreMenu).not.toHaveAttribute('open', '')
        await expect(panel).toBeVisible()
        // A child consumes the first outside click; a second click collapses only the UI.
        await activate(volumeTrigger)
        await outsideBlank()
        await expect(slider).toBeHidden()
        await expect(panel).toBeVisible()
        await outsideBlank()
        await expect(panel).toBeHidden()
        await expect(orb).toBeVisible()
        await expect(audio).toHaveJSProperty('paused', false)
        await activate(orb)
        await activate(mode.getByLabel('播放模式', { exact: true }))
        await outsideBlank()
        await expect(mode.locator('details')).not.toHaveAttribute('open', '')
        await expect(panel).toBeVisible()
        await activate(moreTrigger)
        await outsideBlank()
        await expect(moreMenu).not.toHaveAttribute('open', '')
        await expect(panel).toBeVisible()

        // The popover remains owned by the player when rendered outside its card.
        await activate(volumeTrigger)
        const portal = panel.locator('.dock-volume-popover')
        await portal.evaluate(element => {
          document.body.appendChild(element)
          Object.assign((element as HTMLElement).style, { position: 'fixed', top: '100px', left: '8px', zIndex: '100' })
        })
        const portalSlider = page.locator('.dock-volume-popover').getByLabel('音乐音量', { exact: true })
        try {
          await portalSlider.press('ArrowRight')
          await page.locator('.dock-volume-popover').getByLabel('当前音乐音量', { exact: true }).click()
          await expect(volumeMenu).toHaveAttribute('open', '')
          await expect(panel).toBeVisible()
          await portalSlider.press('ArrowLeft')
          await portalSlider.press('Escape')
          await expect(page.locator('.dock-volume-popover')).toBeHidden()
          await expect(panel).toBeVisible()
        } finally {
          await volumeMenu.evaluate(details => {
            const element = document.querySelector('.dock-volume-popover[data-popover-scope="music-dock"]')!
            element.removeAttribute('style')
            details.appendChild(element)
          })
        }

        await activate(moreTrigger)
        await page.keyboard.press('Escape')
        await expect(moreMenu).not.toHaveAttribute('open', '')
        await expect(panel).toBeVisible()
        await page.locator('body').evaluate(element => { element.tabIndex = -1; element.focus() })
        await page.keyboard.press('Escape')
        await expect(panel).toBeHidden()
        await expect(orb).toBeFocused()
        await activate(orb)
        await expect(audio).toHaveAttribute('data-player-events', '0')
        await panel.getByLabel('音乐播放进度', { exact: true }).evaluate((input: HTMLInputElement) => { input.value = '45'; input.dispatchEvent(new Event('change', { bubbles: true })) })
        await expect(panel.locator('.audio-subtitles')).toHaveText('Chorus')
        await expect(panel.locator('.dock-lyric-neighbor')).toHaveText(['Prelude', 'Outro'])
        await expect(panel.locator('.audio-subtitles')).toHaveCSS('font-weight', '600')
        await activate(panel.getByRole('button', { name: '音轨章节', exact: true }))
        const chapters = panel.locator('.music-chapters')
        await expect(chapters.locator('[data-chapter-index]')).toHaveCount(2)
        await expect(chapters.locator('[aria-current="true"]')).toHaveAttribute('data-chapter-index', '1')
        const beforeCollapse = await audio.evaluate((element: HTMLAudioElement) => element.currentTime)
        await activate(collapse)
        await expect(panel).toBeHidden()
        await expect(orb).toBeVisible()
        await expect(orb).toBeFocused()
        await expect(orb).toHaveCSS('outline-style', 'none')
        await expect(audio).toHaveAttribute('src', firstSource)
        await expect(audio).toHaveAttribute('data-player-events', '0')
        await expect(audio).toHaveJSProperty('volume', 0.35)
        await expect.poll(() => audio.evaluate((element: HTMLAudioElement) => element.currentTime)).toBeGreaterThan(beforeCollapse)
        await activate(orb)
        await expect(mode).toHaveAttribute('data-playback-mode', 'repeat-all')
        await expect(chapters.locator('[aria-current="true"]')).toHaveAttribute('data-chapter-index', '1')
        await activate(chapters.getByRole('button', { name: '关闭章节', exact: true }))
        await expect(audio).toHaveAttribute('data-player-events', '0')

        // Both keyboard and pointer round trips keep a paused seek and the same element.
        await activate(panel.getByRole('button', { name: '暂停音乐', exact: true }))
        await panel.getByLabel('音乐播放进度', { exact: true }).evaluate((input: HTMLInputElement) => { input.value = '12'; input.dispatchEvent(new Event('change', { bubbles: true })) })
        await expect(panel.locator('.audio-subtitles')).toHaveText('Prelude')
        await expect(panel.locator('.dock-lyric-neighbor')).toHaveText(['', 'Chorus'])
        const pausedEvents = await audio.getAttribute('data-player-events')
        await outsideBlank()
        await expect(panel).toBeHidden()
        await expect(orb).toBeVisible()
        await activate(orb)
        await expect(audio).toHaveJSProperty('paused', true)
        await expect(audio).toHaveJSProperty('currentTime', 12)
        await expect(audio).toHaveJSProperty('volume', 0.35)
        await expect(audio).toHaveAttribute('data-player-events', pausedEvents!)
        await expect(mode).toHaveAttribute('data-playback-mode', 'repeat-all')
        await collapse.press('Enter')
        await expect(orb).toBeFocused()
        await expect(orb).toHaveCSS('outline-width', '1px')
        await expect.poll(async () => Number(await ring.evaluate(element => (element as SVGElement).style.strokeDashoffset))).toBeCloseTo(100 - 12 / 90 * 100, 1)
        await page.setViewportSize({ width: mobile ? 1280 : 390, height: 900 })
        await expect(orb).toBeVisible()
        await expect(panel).toBeHidden()
        await orb.press('Enter')
        await expect(collapse).toBeFocused()
        await expect(collapse).toHaveCSS('outline-width', '1px')
        await expect(audio).toHaveJSProperty('paused', true)
        await expect.poll(() => audio.evaluate((element: HTMLAudioElement) => element.currentTime)).toBeCloseTo(12, 1)
        await expect(mode).toHaveAttribute('data-playback-mode', 'repeat-all')
        await expect(audio).toHaveAttribute('data-player-session', 'original')
        await page.setViewportSize({ width, height: 900 })
        await expect(panel).toBeVisible()
        if (navBounds) {
          expect((await nav.boundingBox())!).toEqual(navBounds)
          expect(await nav.evaluate(element => {
            const bounds = element.getBoundingClientRect()
            return !!document.elementFromPoint(bounds.left + bounds.width / 8, bounds.top + bounds.height / 2)?.closest('.mobile-navigation')
          })).toBe(true)
        }
        if (process.env.E2E_AUDIO_SCREENSHOTS) {
          mkdirSync(process.env.E2E_AUDIO_SCREENSHOTS, { recursive: true })
          await page.screenshot({ path: `${process.env.E2E_AUDIO_SCREENSHOTS}/floating-panel-${width}.png` })
        }
        await panel.press('Escape')
        await expect(orb).toBeFocused()
        await expect(panel).toBeHidden()
        if (process.env.E2E_AUDIO_SCREENSHOTS) await page.screenshot({ path: `${process.env.E2E_AUDIO_SCREENSHOTS}/floating-orb-${width}.png` })

        // Queue advancement happens while the orb is the only player surface.
        await activate(orb)
        await activate(panel.getByRole('button', { name: '播放音乐', exact: true }))
        await activate(collapse)
        await expect(panel).toBeHidden()
        await audio.evaluate((element: HTMLAudioElement) => { element.currentTime = element.duration - 0.1 })
        await expect(audio).toHaveAttribute('src', `/api/files/${files[1].id}/preview`)
        await expect(audio).toHaveJSProperty('paused', false)
        await expect(orb).toBeVisible()
        await expect(panel).toBeHidden()
        await activate(orb)
        await expect(panel.locator('.dock-track small')).toContainText('第 2 / 2 轨')
        await expect(panel.locator('.dock-lyrics-empty')).toHaveText('暂无歌词/字幕')
        await expect.poll(async () => (await panel.locator('.dock-lyrics').boundingBox())?.height).toBe(lyricBounds.height)

        // Low-frequency actions remain in the detailed player's menu on every device.
        await panel.getByLabel('播放器更多操作', { exact: true }).click()
        await panel.getByRole('button', { name: '结束播放', exact: true }).click()
        await expect(page.locator('.music-orb, .music-dock')).toHaveCount(0)
        await expect(audio).toHaveJSProperty('paused', true)
        await expect(audio).not.toHaveAttribute('src')
        await expect(audio).toHaveJSProperty('currentTime', 0)
        await expect(page.locator('audio[aria-hidden="true"]')).not.toHaveAttribute('src')
        expect(await page.evaluate(key => localStorage.getItem(key), `revaro-listening:${process.env.E2E_USERNAME || 'admin'}`)).toBe('')
        await expect(page.locator('audio')).toHaveCount(audioCount)
        await page.reload()
        await expect(page.locator('.music-orb, .music-dock')).toHaveCount(0)
        await page.getByLabel('选择集合', { exact: true }).click()
        await page.getByRole('button', { name: `${prefix} · 2`, exact: true }).click()
        await page.getByRole('button', { name: `打开 ${files[0].name}`, exact: true }).click()
        await expect(orb).toBeVisible()
        await expect(panel).toBeHidden()
        await expect(mode).toHaveAttribute('data-playback-mode', 'sequential')
        await activate(orb)
        await panel.getByLabel('播放器更多操作', { exact: true }).click()
        await panel.getByRole('button', { name: '结束播放', exact: true }).click()
        await expect(page.locator('.music-orb, .music-dock')).toHaveCount(0)
        await expect(audio).toHaveJSProperty('paused', true)
        await expect(audio).not.toHaveAttribute('src')

        // Finishing the final sequential item also clears the player UI.
        await page.getByRole('button', { name: `打开 ${files[1].name}`, exact: true }).click()
        await expect(audio).toHaveJSProperty('paused', false)
        await audio.evaluate((element: HTMLAudioElement) => { element.currentTime = element.duration - 0.1 })
        await expect(page.locator('.music-orb, .music-dock')).toHaveCount(0)
        await expect(audio).toHaveJSProperty('paused', true)
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
        expect(errors).toEqual([])
      } finally {
        await pauseMusic(page)
        if (collectionId) await page.request.delete(`/api/library/collections/${collectionId}`, { headers })
        await page.request.delete(`/api/files/${id}`, { headers })
        await page.request.delete(`/api/trash/${id}`, { headers })
      }
    })
  })
}
