import { expect, test } from '@playwright/test'
import { login } from './helpers'

const root = '00000000-0000-0000-0000-000000000000'

test('one persistent header serves every page, with working tools, routes and global import', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await login(page)
  await page.evaluate(() => { (window as any).__header = document.querySelector('header.topbar') })
  const nav = page.getByRole('navigation', { name: '主导航', exact: true })
  for (const label of ['首页', '阅读', '音乐', '图库', '文件']) {
    await nav.getByRole('link', { name: label, exact: true }).click()
    await expect(page.locator('header.topbar')).toHaveCount(1)
    await expect(page.locator('.app-shell header.topbar, .library-topbar')).toHaveCount(0)
    await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', label)
    expect(await page.evaluate(() => (window as any).__header === document.querySelector('header.topbar'))).toBe(true)
    await page.getByLabel('打开账户设置', { exact: true }).click()
    await expect(page.locator('.management')).toBeVisible()
    await expect(page.locator('.management > h3').first()).toHaveText('分享管理与运行状态')
    await expect(page.locator('.management summary, .management details')).toHaveCount(0)
    await page.locator('.account-modal').getByRole('button', { name: '关闭', exact: true }).click()
    await page.locator('.task-center > summary').click()
    await expect(page.locator('.task-panel')).toBeVisible()
    await page.locator('.task-center > summary').click()
  }
  await page.getByLabel('回到首页', { exact: true }).click()
  await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', '首页')
  await page.getByLabel('打开回收站', { exact: true }).click()
  await expect(page.getByRole('heading', { name: '回收站', exact: true })).toBeVisible()
  await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', '文件')
  await expect(page.locator('.topbar').getByLabel('上传', { exact: true })).toHaveAttribute('aria-disabled', 'true')
  await nav.getByRole('link', { name: '阅读', exact: true }).click()
  await expect(page.locator('.topbar').getByLabel('上传', { exact: true })).toHaveAttribute('aria-disabled', 'false')
  const chooser = page.waitForEvent('filechooser')
  await page.locator('.topbar').getByLabel('上传', { exact: true }).click()
  await page.getByRole('button', { name: '上传文件', exact: true }).click()
  const name = `global-import-${Date.now()}.txt`
  await (await chooser).setFiles({ name, mimeType: 'text/plain', buffer: Buffer.from('全局导入测试') })
  await expect.poll(async () => (await (await page.request.get(`/api/library/items?q=${name}`)).json()).total).toBe(1)
  const item = (await (await page.request.get(`/api/library/items?q=${name}`)).json()).items[0]
  expect(item.file.parent_id).toBe(root)
  await expect(page.getByRole('button', { name: `打开 ${name}`, exact: true })).toBeVisible()
  await nav.getByRole('link', { name: '音乐', exact: true }).click()
  await page.goBack()
  await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', '阅读')
  await page.goForward()
  await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', '音乐')
  const folderName = `header-folder-${Date.now()}`
  const response = await page.request.post('/api/directories', {
    headers: { Origin: new URL(page.url()).origin }, data: { name: folderName, parent_id: root },
  })
  expect(response.ok()).toBe(true)
  const folder = await response.json()
  await page.goto(`/f/${folder.id}`)
  await expect(page.getByRole('heading', { name: folderName, exact: true })).toBeVisible()
  await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', '文件')
  await nav.getByRole('link', { name: '阅读', exact: true }).click()
  await page.goBack()
  await expect(page.getByRole('heading', { name: folderName, exact: true })).toBeVisible()
  await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', '文件')
  await nav.getByRole('link', { name: '文件', exact: true }).click()
  await expect(page.getByRole('heading', { name: '我的文件', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('shared navigation, tools and search remain usable across mobile breakpoints', async ({ page }) => {
  await login(page)
  for (const width of [850, 760, 390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    await expect(page.locator('header.topbar')).toHaveCount(1)
    const nav = page.getByRole('navigation', { name: '移动端导航', exact: true })
    expect(await nav.getByRole('link').evaluateAll(links => links.map(link => link.getAttribute('aria-label')))).toEqual(['首页', '阅读', '音乐', '图库', '文件'])
    for (const label of ['阅读', '音乐', '图库', '文件']) {
      await nav.getByRole('link', { name: label, exact: true }).click()
      await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', label)
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.getByLabel('打开搜索', { exact: true }).click()
    await expect(page.getByLabel('搜索文件名')).toBeFocused()
    const bounds = await page.locator('.search-surface').boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width)
    await nav.getByRole('link', { name: '首页', exact: true }).click()
    await expect(page.locator('.topbar.searching')).toHaveCount(0)
    await page.getByLabel('打开账户与工具菜单', { exact: true }).click()
    await page.getByRole('button', { name: '账户设置', exact: true }).click()
    await expect(page.locator('.management')).toBeVisible()
    await page.locator('.account-modal').getByRole('button', { name: '关闭', exact: true }).click()
    await page.getByLabel('打开账户与工具菜单', { exact: true }).click()
    await page.getByRole('button', { name: '回收站', exact: true }).click()
    await expect(page.getByRole('heading', { name: '回收站', exact: true })).toBeVisible()
    await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', '文件')
    await nav.getByRole('link', { name: '文件', exact: true }).click()
    await expect(page.getByRole('heading', { name: '我的文件', exact: true })).toBeVisible()
  }
  await page.setViewportSize({ width: 851, height: 844 })
  await expect(page.getByRole('navigation', { name: '主导航', exact: true })).toBeVisible()
  await expect(page.getByRole('navigation', { name: '移动端导航', exact: true })).toBeHidden()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(851)
  const desktop = page.getByRole('navigation', { name: '主导航', exact: true })
  const actions = await page.locator('.topbar .top-actions').boundingBox()
  const navigation = await desktop.boundingBox()
  expect(actions!.x).toBeGreaterThanOrEqual(navigation!.x + navigation!.width)
  await page.getByLabel('打开搜索', { exact: true }).click()
  await expect(page.getByLabel('搜索文件名')).toBeFocused()
  await expect(desktop).toBeHidden()
  await page.keyboard.press('Escape')
  await expect(desktop).toBeVisible()
  await desktop.getByRole('link', { name: '音乐', exact: true }).click()
  await expect(desktop.locator('[aria-current="page"]')).toHaveAttribute('aria-label', '音乐')
  await expect(page.locator('.topbar.searching')).toHaveCount(0)
})
