import { expect, test } from '@playwright/test'
import { login, navigate, openTopbarMenu } from './helpers'

const root = '00000000-0000-0000-0000-000000000000'

test('one persistent header serves every page, with working tools, routes and global import', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await login(page)
  await page.evaluate(() => { (window as any).__header = document.querySelector('header.topbar') })
  const nav = page.getByRole('navigation', { name: '主导航', exact: true })
  for (const label of ['首页', '书籍', '音乐', '图片', '视频', '文件', '回收站']) {
    await nav.getByRole('link', { name: label, exact: true }).click()
    await expect(page.locator('header.topbar')).toHaveCount(1)
    await expect(page.locator('.app-shell header.topbar, .library-topbar')).toHaveCount(0)
    await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', label)
    expect(await page.evaluate(() => (window as any).__header === document.querySelector('header.topbar'))).toBe(true)
    await page.getByLabel('打开账户设置', { exact: true }).click()
    await expect(page.locator('.account-modal')).toBeVisible()
    await expect(page.locator('.account-modal')).not.toContainText('公开链接')
    await page.locator('.account-modal').getByRole('button', { name: '关闭', exact: true }).click()
  }
  await page.getByLabel('回到首页', { exact: true }).click()
  await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', '首页')
  await nav.getByRole('link', { name: '回收站', exact: true }).click()
  await expect(page.locator('.trash-toolbar')).toBeVisible()
  await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', '回收站')
  await expect(page.locator('.topbar').getByLabel('上传', { exact: true })).toHaveAttribute('aria-disabled', 'true')
  await nav.getByRole('link', { name: '书籍', exact: true }).click()
  await expect(page.locator('.topbar').getByLabel('上传', { exact: true })).toHaveAttribute('aria-disabled', 'false')
  const chooser = page.waitForEvent('filechooser')
  await openTopbarMenu(page)
  await page.locator('.topbar').getByLabel('上传', { exact: true }).click()
  await page.getByRole('button', { name: '上传文件', exact: true }).click()
  const name = `global-import-${Date.now()}.txt`
  await (await chooser).setFiles({ name, mimeType: 'text/plain', buffer: Buffer.from('全局导入测试') })
  await expect.poll(async () => (await (await page.request.get(`/api/library/items?q=${name}`)).json()).total).toBe(1)
  const item = (await (await page.request.get(`/api/library/items?q=${name}`)).json()).items[0]
  expect(item.file.parent_id).toBe(root)
  await expect(page.getByRole('button', { name: `打开 ${name}`, exact: true })).toBeVisible()
  await nav.getByRole('link', { name: '音乐', exact: true }).click()
  await page.goBack()
  await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', '书籍')
  await page.goForward()
  await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', '音乐')
  const folderName = `header-folder-${Date.now()}`
  const response = await page.request.post('/api/directories', {
    headers: { Origin: new URL(page.url()).origin }, data: { name: folderName, parent_id: root },
  })
  expect(response.ok()).toBe(true)
  const folder = await response.json()
  await page.goto(`/f/${folder.id}`)
  await expect(page.getByRole('navigation', { name: '当前路径', exact: true }).getByRole('button', { name: folderName, exact: true })).toBeVisible()
  await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', '文件')
  await nav.getByRole('link', { name: '书籍', exact: true }).click()
  await page.goBack()
  await expect(page.getByRole('navigation', { name: '当前路径', exact: true }).getByRole('button', { name: folderName, exact: true })).toBeVisible()
  await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', '文件')
  await nav.getByRole('link', { name: '文件', exact: true }).click()
  await expect(page.getByRole('navigation', { name: '当前路径', exact: true }).getByRole('button', { name: '我的文件', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('shared navigation, tools and search remain usable across mobile breakpoints', async ({ page }) => {
  await login(page)
  for (const width of [850, 760, 390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    await expect(page.locator('header.topbar')).toHaveCount(1)
    const nav = page.getByRole('navigation', { name: '移动端导航', exact: true })
    const icons = nav.locator(':scope > a, :scope > .mobile-library-menu > details > summary')
    await expect(icons).toHaveCount(4)
    expect(await icons.evaluateAll(elements => elements.map(element => element.getAttribute('aria-label')))).toEqual(['首页', '文件', '内容库', '回收站'])
    const positions = await icons.evaluateAll(elements => elements.map(element => {
      const bounds = element.getBoundingClientRect()
      return { x: bounds.x, width: bounds.width }
    }))
    for (let index = 0; index < positions.length; index++) {
      expect(positions[index].width).toBeCloseTo(width / 4, 1)
      expect(positions[index].x).toBeCloseTo(index * width / 4, 1)
    }
    for (const label of ['书籍', '音乐', '图片', '视频', '文件']) {
      await navigate(page, label)
      await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', label === '图片' ? '图库' : label)
      await expect(nav.getByLabel('内容库', { exact: true })).toHaveAttribute('aria-expanded', 'false')
      await expect(nav.locator('.mobile-library-menu')).toHaveClass(label === '文件' ? 'mobile-library-menu' : 'mobile-library-menu active')
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.getByLabel('打开搜索', { exact: true }).click()
    await expect(page.getByLabel('搜索文件名')).toBeFocused()
    const bounds = await page.locator('.search-surface').boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width)
    await nav.getByRole('link', { name: '首页', exact: true }).click()
    await expect(page.locator('.topbar.searching')).toHaveCount(0)
    await page.getByLabel('打开账户设置', { exact: true }).click()
    await expect(page.locator('.account-modal')).toBeVisible()
    await page.locator('.account-modal').getByRole('button', { name: '关闭', exact: true }).click()
    await nav.getByRole('link', { name: '回收站', exact: true }).click()
    await expect(page.locator('.trash-toolbar')).toBeVisible()
    await expect(nav.locator('[aria-current="page"]')).toHaveAttribute('aria-label', '回收站')
    await nav.getByRole('link', { name: '文件', exact: true }).click()
    await expect(page.getByRole('navigation', { name: '当前路径', exact: true }).getByRole('button', { name: '我的文件', exact: true })).toBeVisible()
  }
  await page.setViewportSize({ width: 851, height: 844 })
  await expect(page.getByRole('navigation', { name: '主导航', exact: true })).toBeVisible()
  await expect(page.getByRole('navigation', { name: '移动端导航', exact: true })).toBeHidden()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(851)
  const desktop = page.getByRole('navigation', { name: '主导航', exact: true })
  const actions = await page.locator('.topbar .top-actions').boundingBox()
  const navigation = await desktop.boundingBox()
  expect(actions!.x).toBeGreaterThanOrEqual(navigation!.x + navigation!.width)
  await page.getByLabel('打开搜索', { exact: true }).click()
  await expect(page.getByLabel('搜索文件名')).toBeFocused()
  await expect(desktop).toBeHidden()
  await page.keyboard.press('Escape')
  await expect(desktop).toBeVisible()
  await desktop.getByRole('link', { name: '音乐', exact: true }).click()
  await expect(desktop.locator('[aria-current="page"]')).toHaveAttribute('aria-label', '音乐')
  await expect(page.locator('.topbar.searching')).toHaveCount(0)
})

test('mobile library menu supports dismissal, keyboard focus, history and desktop resizing', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await login(page)
  const nav = page.getByRole('navigation', { name: '移动端导航', exact: true })
  const trigger = nav.getByLabel('内容库', { exact: true })
  const panel = nav.locator('.mobile-library-menu-panel')
  await trigger.click()
  await expect(panel).toBeVisible()
  expect(await panel.getByRole('link').allTextContents()).toEqual(['书籍', '音乐', '图库', '视频'])
  const bounds = (await panel.boundingBox())!
  expect(bounds.x).toBe(0)
  expect(bounds.width).toBe(390)
  expect(bounds.y + bounds.height).toBe(844)
  await expect(page.locator('body')).toHaveCSS('overflow', 'hidden')
  const close = nav.getByRole('button', { name: '关闭内容库菜单', exact: true })
  await close.focus()
  await page.keyboard.press('Shift+Tab')
  await expect(panel.getByRole('link', { name: '视频', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(close).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(panel).toBeHidden()
  await expect(trigger).toBeFocused()
  await trigger.press('Enter')
  await close.click()
  await expect(panel).toBeHidden()
  await trigger.click()
  await nav.locator('.topbar-menu-backdrop').click({ position: { x: 1, y: 1 } })
  await expect(panel).toBeHidden()
  await navigate(page, '书籍')
  await navigate(page, '音乐')
  await page.goBack()
  await expect(page).toHaveURL(/\/library$/)
  await trigger.click()
  await expect(panel.getByRole('link', { name: '书籍', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.goForward()
  await expect(panel).toBeHidden()
  await expect(page).toHaveURL(/\/music$/)
  await trigger.click()
  await page.setViewportSize({ width: 851, height: 844 })
  await expect(nav).toBeHidden()
  await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden')
  const desktop = page.getByRole('navigation', { name: '主导航', exact: true })
  await expect(desktop.getByRole('link')).toHaveCount(7)
  await expect(desktop.getByRole('link', { name: '音乐', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
})
