-- Add independent video indexing, preserving collections, membership and library state.
DROP TRIGGER library_file_insert;
DROP TRIGGER library_file_update;
CREATE TEMP TABLE saved_collections AS SELECT * FROM library_collections;
CREATE TEMP TABLE saved_members AS SELECT * FROM library_collection_items;
DROP TABLE library_collection_items;
DROP TABLE library_collections;
DROP TABLE library_items;
-- Content is indexed without relocating or copying original files.
CREATE TABLE library_items (
 file_id TEXT PRIMARY KEY REFERENCES files(id) ON DELETE CASCADE,
 kind TEXT NOT NULL CHECK(kind IN ('book','audio','image','video'))
);
CREATE INDEX library_items_kind ON library_items(kind,file_id);
CREATE TABLE library_collections (
 id TEXT PRIMARY KEY,
 name TEXT NOT NULL,
 kind TEXT NOT NULL CHECK(kind IN ('book','audio','image','video')),
 created_at TEXT NOT NULL
);
CREATE TABLE library_collection_items (
 collection_id TEXT NOT NULL REFERENCES library_collections(id) ON DELETE CASCADE,
 file_id TEXT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
 position INTEGER NOT NULL,
 PRIMARY KEY(collection_id,file_id)
);
CREATE INDEX library_collection_order ON library_collection_items(collection_id,position,file_id);
INSERT INTO library_items(file_id,kind) SELECT id,CASE WHEN (lower(COALESCE(mime_type,'')) LIKE 'video/%' OR lower(name) GLOB '?*.mp4' OR lower(name) GLOB '?*.webm' OR lower(name) GLOB '?*.mov' OR lower(name) GLOB '?*.m4v' OR lower(name) GLOB '?*.mkv' OR lower(name) GLOB '?*.avi' OR lower(name) GLOB '?*.ogv' OR lower(name) GLOB '?*.mpg' OR lower(name) GLOB '?*.mpeg' OR lower(name) GLOB '?*.wmv' OR lower(name) GLOB '?*.flv' OR lower(name) GLOB '?*.ts' OR lower(name) GLOB '?*.m2ts' OR lower(name) GLOB '?*.mts') THEN 'video' WHEN (lower(name) GLOB '?*.epub' OR lower(name) GLOB '?*.txt') THEN 'book' WHEN (lower(COALESCE(mime_type,'')) LIKE 'audio/%' OR lower(name) GLOB '?*.mp3' OR lower(name) GLOB '?*.wav' OR lower(name) GLOB '?*.flac' OR lower(name) GLOB '?*.m4a' OR lower(name) GLOB '?*.aac' OR lower(name) GLOB '?*.ogg' OR lower(name) GLOB '?*.oga' OR lower(name) GLOB '?*.opus' OR lower(name) GLOB '?*.wma' OR lower(name) GLOB '?*.aif' OR lower(name) GLOB '?*.aiff' OR lower(name) GLOB '?*.ape') THEN 'audio' WHEN (lower(COALESCE(mime_type,'')) IN ('image/jpeg','image/png','image/gif','image/webp','image/avif') OR lower(name) GLOB '?*.jpg' OR lower(name) GLOB '?*.jpeg' OR lower(name) GLOB '?*.png' OR lower(name) GLOB '?*.gif' OR lower(name) GLOB '?*.webp' OR lower(name) GLOB '?*.avif') THEN 'image' ELSE NULL END FROM files WHERE kind='file' AND status='ready' AND (CASE WHEN (lower(COALESCE(mime_type,'')) LIKE 'video/%' OR lower(name) GLOB '?*.mp4' OR lower(name) GLOB '?*.webm' OR lower(name) GLOB '?*.mov' OR lower(name) GLOB '?*.m4v' OR lower(name) GLOB '?*.mkv' OR lower(name) GLOB '?*.avi' OR lower(name) GLOB '?*.ogv' OR lower(name) GLOB '?*.mpg' OR lower(name) GLOB '?*.mpeg' OR lower(name) GLOB '?*.wmv' OR lower(name) GLOB '?*.flv' OR lower(name) GLOB '?*.ts' OR lower(name) GLOB '?*.m2ts' OR lower(name) GLOB '?*.mts') THEN 'video' WHEN (lower(name) GLOB '?*.epub' OR lower(name) GLOB '?*.txt') THEN 'book' WHEN (lower(COALESCE(mime_type,'')) LIKE 'audio/%' OR lower(name) GLOB '?*.mp3' OR lower(name) GLOB '?*.wav' OR lower(name) GLOB '?*.flac' OR lower(name) GLOB '?*.m4a' OR lower(name) GLOB '?*.aac' OR lower(name) GLOB '?*.ogg' OR lower(name) GLOB '?*.oga' OR lower(name) GLOB '?*.opus' OR lower(name) GLOB '?*.wma' OR lower(name) GLOB '?*.aif' OR lower(name) GLOB '?*.aiff' OR lower(name) GLOB '?*.ape') THEN 'audio' WHEN (lower(COALESCE(mime_type,'')) IN ('image/jpeg','image/png','image/gif','image/webp','image/avif') OR lower(name) GLOB '?*.jpg' OR lower(name) GLOB '?*.jpeg' OR lower(name) GLOB '?*.png' OR lower(name) GLOB '?*.gif' OR lower(name) GLOB '?*.webp' OR lower(name) GLOB '?*.avif') THEN 'image' ELSE NULL END) IS NOT NULL;
CREATE TRIGGER library_file_insert AFTER INSERT ON files
BEGIN
 DELETE FROM library_items WHERE file_id=NEW.id AND (NEW.kind<>'file' OR NEW.status<>'ready' OR (CASE WHEN (lower(COALESCE(NEW.mime_type,'')) LIKE 'video/%' OR lower(NEW.name) GLOB '?*.mp4' OR lower(NEW.name) GLOB '?*.webm' OR lower(NEW.name) GLOB '?*.mov' OR lower(NEW.name) GLOB '?*.m4v' OR lower(NEW.name) GLOB '?*.mkv' OR lower(NEW.name) GLOB '?*.avi' OR lower(NEW.name) GLOB '?*.ogv' OR lower(NEW.name) GLOB '?*.mpg' OR lower(NEW.name) GLOB '?*.mpeg' OR lower(NEW.name) GLOB '?*.wmv' OR lower(NEW.name) GLOB '?*.flv' OR lower(NEW.name) GLOB '?*.ts' OR lower(NEW.name) GLOB '?*.m2ts' OR lower(NEW.name) GLOB '?*.mts') THEN 'video' WHEN (lower(NEW.name) GLOB '?*.epub' OR lower(NEW.name) GLOB '?*.txt') THEN 'book' WHEN (lower(COALESCE(NEW.mime_type,'')) LIKE 'audio/%' OR lower(NEW.name) GLOB '?*.mp3' OR lower(NEW.name) GLOB '?*.wav' OR lower(NEW.name) GLOB '?*.flac' OR lower(NEW.name) GLOB '?*.m4a' OR lower(NEW.name) GLOB '?*.aac' OR lower(NEW.name) GLOB '?*.ogg' OR lower(NEW.name) GLOB '?*.oga' OR lower(NEW.name) GLOB '?*.opus' OR lower(NEW.name) GLOB '?*.wma' OR lower(NEW.name) GLOB '?*.aif' OR lower(NEW.name) GLOB '?*.aiff' OR lower(NEW.name) GLOB '?*.ape') THEN 'audio' WHEN (lower(COALESCE(NEW.mime_type,'')) IN ('image/jpeg','image/png','image/gif','image/webp','image/avif') OR lower(NEW.name) GLOB '?*.jpg' OR lower(NEW.name) GLOB '?*.jpeg' OR lower(NEW.name) GLOB '?*.png' OR lower(NEW.name) GLOB '?*.gif' OR lower(NEW.name) GLOB '?*.webp' OR lower(NEW.name) GLOB '?*.avif') THEN 'image' ELSE NULL END) IS NULL);
 INSERT INTO library_items(file_id,kind) SELECT NEW.id,CASE WHEN (lower(COALESCE(NEW.mime_type,'')) LIKE 'video/%' OR lower(NEW.name) GLOB '?*.mp4' OR lower(NEW.name) GLOB '?*.webm' OR lower(NEW.name) GLOB '?*.mov' OR lower(NEW.name) GLOB '?*.m4v' OR lower(NEW.name) GLOB '?*.mkv' OR lower(NEW.name) GLOB '?*.avi' OR lower(NEW.name) GLOB '?*.ogv' OR lower(NEW.name) GLOB '?*.mpg' OR lower(NEW.name) GLOB '?*.mpeg' OR lower(NEW.name) GLOB '?*.wmv' OR lower(NEW.name) GLOB '?*.flv' OR lower(NEW.name) GLOB '?*.ts' OR lower(NEW.name) GLOB '?*.m2ts' OR lower(NEW.name) GLOB '?*.mts') THEN 'video' WHEN (lower(NEW.name) GLOB '?*.epub' OR lower(NEW.name) GLOB '?*.txt') THEN 'book' WHEN (lower(COALESCE(NEW.mime_type,'')) LIKE 'audio/%' OR lower(NEW.name) GLOB '?*.mp3' OR lower(NEW.name) GLOB '?*.wav' OR lower(NEW.name) GLOB '?*.flac' OR lower(NEW.name) GLOB '?*.m4a' OR lower(NEW.name) GLOB '?*.aac' OR lower(NEW.name) GLOB '?*.ogg' OR lower(NEW.name) GLOB '?*.oga' OR lower(NEW.name) GLOB '?*.opus' OR lower(NEW.name) GLOB '?*.wma' OR lower(NEW.name) GLOB '?*.aif' OR lower(NEW.name) GLOB '?*.aiff' OR lower(NEW.name) GLOB '?*.ape') THEN 'audio' WHEN (lower(COALESCE(NEW.mime_type,'')) IN ('image/jpeg','image/png','image/gif','image/webp','image/avif') OR lower(NEW.name) GLOB '?*.jpg' OR lower(NEW.name) GLOB '?*.jpeg' OR lower(NEW.name) GLOB '?*.png' OR lower(NEW.name) GLOB '?*.gif' OR lower(NEW.name) GLOB '?*.webp' OR lower(NEW.name) GLOB '?*.avif') THEN 'image' ELSE NULL END
 WHERE NEW.kind='file' AND NEW.status='ready' AND (CASE WHEN (lower(COALESCE(NEW.mime_type,'')) LIKE 'video/%' OR lower(NEW.name) GLOB '?*.mp4' OR lower(NEW.name) GLOB '?*.webm' OR lower(NEW.name) GLOB '?*.mov' OR lower(NEW.name) GLOB '?*.m4v' OR lower(NEW.name) GLOB '?*.mkv' OR lower(NEW.name) GLOB '?*.avi' OR lower(NEW.name) GLOB '?*.ogv' OR lower(NEW.name) GLOB '?*.mpg' OR lower(NEW.name) GLOB '?*.mpeg' OR lower(NEW.name) GLOB '?*.wmv' OR lower(NEW.name) GLOB '?*.flv' OR lower(NEW.name) GLOB '?*.ts' OR lower(NEW.name) GLOB '?*.m2ts' OR lower(NEW.name) GLOB '?*.mts') THEN 'video' WHEN (lower(NEW.name) GLOB '?*.epub' OR lower(NEW.name) GLOB '?*.txt') THEN 'book' WHEN (lower(COALESCE(NEW.mime_type,'')) LIKE 'audio/%' OR lower(NEW.name) GLOB '?*.mp3' OR lower(NEW.name) GLOB '?*.wav' OR lower(NEW.name) GLOB '?*.flac' OR lower(NEW.name) GLOB '?*.m4a' OR lower(NEW.name) GLOB '?*.aac' OR lower(NEW.name) GLOB '?*.ogg' OR lower(NEW.name) GLOB '?*.oga' OR lower(NEW.name) GLOB '?*.opus' OR lower(NEW.name) GLOB '?*.wma' OR lower(NEW.name) GLOB '?*.aif' OR lower(NEW.name) GLOB '?*.aiff' OR lower(NEW.name) GLOB '?*.ape') THEN 'audio' WHEN (lower(COALESCE(NEW.mime_type,'')) IN ('image/jpeg','image/png','image/gif','image/webp','image/avif') OR lower(NEW.name) GLOB '?*.jpg' OR lower(NEW.name) GLOB '?*.jpeg' OR lower(NEW.name) GLOB '?*.png' OR lower(NEW.name) GLOB '?*.gif' OR lower(NEW.name) GLOB '?*.webp' OR lower(NEW.name) GLOB '?*.avif') THEN 'image' ELSE NULL END) IS NOT NULL
 ON CONFLICT(file_id) DO UPDATE SET kind=excluded.kind;
END;
CREATE TRIGGER library_file_update AFTER UPDATE OF name,mime_type,status ON files
BEGIN
 DELETE FROM library_items WHERE file_id=NEW.id AND (NEW.kind<>'file' OR NEW.status<>'ready' OR (CASE WHEN (lower(COALESCE(NEW.mime_type,'')) LIKE 'video/%' OR lower(NEW.name) GLOB '?*.mp4' OR lower(NEW.name) GLOB '?*.webm' OR lower(NEW.name) GLOB '?*.mov' OR lower(NEW.name) GLOB '?*.m4v' OR lower(NEW.name) GLOB '?*.mkv' OR lower(NEW.name) GLOB '?*.avi' OR lower(NEW.name) GLOB '?*.ogv' OR lower(NEW.name) GLOB '?*.mpg' OR lower(NEW.name) GLOB '?*.mpeg' OR lower(NEW.name) GLOB '?*.wmv' OR lower(NEW.name) GLOB '?*.flv' OR lower(NEW.name) GLOB '?*.ts' OR lower(NEW.name) GLOB '?*.m2ts' OR lower(NEW.name) GLOB '?*.mts') THEN 'video' WHEN (lower(NEW.name) GLOB '?*.epub' OR lower(NEW.name) GLOB '?*.txt') THEN 'book' WHEN (lower(COALESCE(NEW.mime_type,'')) LIKE 'audio/%' OR lower(NEW.name) GLOB '?*.mp3' OR lower(NEW.name) GLOB '?*.wav' OR lower(NEW.name) GLOB '?*.flac' OR lower(NEW.name) GLOB '?*.m4a' OR lower(NEW.name) GLOB '?*.aac' OR lower(NEW.name) GLOB '?*.ogg' OR lower(NEW.name) GLOB '?*.oga' OR lower(NEW.name) GLOB '?*.opus' OR lower(NEW.name) GLOB '?*.wma' OR lower(NEW.name) GLOB '?*.aif' OR lower(NEW.name) GLOB '?*.aiff' OR lower(NEW.name) GLOB '?*.ape') THEN 'audio' WHEN (lower(COALESCE(NEW.mime_type,'')) IN ('image/jpeg','image/png','image/gif','image/webp','image/avif') OR lower(NEW.name) GLOB '?*.jpg' OR lower(NEW.name) GLOB '?*.jpeg' OR lower(NEW.name) GLOB '?*.png' OR lower(NEW.name) GLOB '?*.gif' OR lower(NEW.name) GLOB '?*.webp' OR lower(NEW.name) GLOB '?*.avif') THEN 'image' ELSE NULL END) IS NULL);
 INSERT INTO library_items(file_id,kind) SELECT NEW.id,CASE WHEN (lower(COALESCE(NEW.mime_type,'')) LIKE 'video/%' OR lower(NEW.name) GLOB '?*.mp4' OR lower(NEW.name) GLOB '?*.webm' OR lower(NEW.name) GLOB '?*.mov' OR lower(NEW.name) GLOB '?*.m4v' OR lower(NEW.name) GLOB '?*.mkv' OR lower(NEW.name) GLOB '?*.avi' OR lower(NEW.name) GLOB '?*.ogv' OR lower(NEW.name) GLOB '?*.mpg' OR lower(NEW.name) GLOB '?*.mpeg' OR lower(NEW.name) GLOB '?*.wmv' OR lower(NEW.name) GLOB '?*.flv' OR lower(NEW.name) GLOB '?*.ts' OR lower(NEW.name) GLOB '?*.m2ts' OR lower(NEW.name) GLOB '?*.mts') THEN 'video' WHEN (lower(NEW.name) GLOB '?*.epub' OR lower(NEW.name) GLOB '?*.txt') THEN 'book' WHEN (lower(COALESCE(NEW.mime_type,'')) LIKE 'audio/%' OR lower(NEW.name) GLOB '?*.mp3' OR lower(NEW.name) GLOB '?*.wav' OR lower(NEW.name) GLOB '?*.flac' OR lower(NEW.name) GLOB '?*.m4a' OR lower(NEW.name) GLOB '?*.aac' OR lower(NEW.name) GLOB '?*.ogg' OR lower(NEW.name) GLOB '?*.oga' OR lower(NEW.name) GLOB '?*.opus' OR lower(NEW.name) GLOB '?*.wma' OR lower(NEW.name) GLOB '?*.aif' OR lower(NEW.name) GLOB '?*.aiff' OR lower(NEW.name) GLOB '?*.ape') THEN 'audio' WHEN (lower(COALESCE(NEW.mime_type,'')) IN ('image/jpeg','image/png','image/gif','image/webp','image/avif') OR lower(NEW.name) GLOB '?*.jpg' OR lower(NEW.name) GLOB '?*.jpeg' OR lower(NEW.name) GLOB '?*.png' OR lower(NEW.name) GLOB '?*.gif' OR lower(NEW.name) GLOB '?*.webp' OR lower(NEW.name) GLOB '?*.avif') THEN 'image' ELSE NULL END
 WHERE NEW.kind='file' AND NEW.status='ready' AND (CASE WHEN (lower(COALESCE(NEW.mime_type,'')) LIKE 'video/%' OR lower(NEW.name) GLOB '?*.mp4' OR lower(NEW.name) GLOB '?*.webm' OR lower(NEW.name) GLOB '?*.mov' OR lower(NEW.name) GLOB '?*.m4v' OR lower(NEW.name) GLOB '?*.mkv' OR lower(NEW.name) GLOB '?*.avi' OR lower(NEW.name) GLOB '?*.ogv' OR lower(NEW.name) GLOB '?*.mpg' OR lower(NEW.name) GLOB '?*.mpeg' OR lower(NEW.name) GLOB '?*.wmv' OR lower(NEW.name) GLOB '?*.flv' OR lower(NEW.name) GLOB '?*.ts' OR lower(NEW.name) GLOB '?*.m2ts' OR lower(NEW.name) GLOB '?*.mts') THEN 'video' WHEN (lower(NEW.name) GLOB '?*.epub' OR lower(NEW.name) GLOB '?*.txt') THEN 'book' WHEN (lower(COALESCE(NEW.mime_type,'')) LIKE 'audio/%' OR lower(NEW.name) GLOB '?*.mp3' OR lower(NEW.name) GLOB '?*.wav' OR lower(NEW.name) GLOB '?*.flac' OR lower(NEW.name) GLOB '?*.m4a' OR lower(NEW.name) GLOB '?*.aac' OR lower(NEW.name) GLOB '?*.ogg' OR lower(NEW.name) GLOB '?*.oga' OR lower(NEW.name) GLOB '?*.opus' OR lower(NEW.name) GLOB '?*.wma' OR lower(NEW.name) GLOB '?*.aif' OR lower(NEW.name) GLOB '?*.aiff' OR lower(NEW.name) GLOB '?*.ape') THEN 'audio' WHEN (lower(COALESCE(NEW.mime_type,'')) IN ('image/jpeg','image/png','image/gif','image/webp','image/avif') OR lower(NEW.name) GLOB '?*.jpg' OR lower(NEW.name) GLOB '?*.jpeg' OR lower(NEW.name) GLOB '?*.png' OR lower(NEW.name) GLOB '?*.gif' OR lower(NEW.name) GLOB '?*.webp' OR lower(NEW.name) GLOB '?*.avif') THEN 'image' ELSE NULL END) IS NOT NULL
 ON CONFLICT(file_id) DO UPDATE SET kind=excluded.kind;
END;
INSERT INTO library_collections SELECT * FROM saved_collections;
INSERT INTO library_collection_items SELECT * FROM saved_members;
DROP TABLE saved_collections;
DROP TABLE saved_members;
