import { expect, test } from '@playwright/test'
import { login } from './helpers'

test('登录后状态球通过 SSE 展开并关闭系统状态',async({page})=>{
  await login(page)
  await expect(page.locator('.system-status.ok summary')).toBeVisible()
  await page.locator('[aria-label="打开系统状态"]').click()
  const panel=page.locator('.status-panel')
  await expect(panel).toBeVisible()
  await expect(panel.getByText('数据库')).toBeVisible()
  await expect(panel.getByText('网盘存储使用量')).toBeVisible()
  await expect(panel.locator('.status-grid > *')).toHaveCount(3)
  await expect(panel.getByText('任务', {exact:true})).toHaveCount(0)
  await expect(panel.getByText('清理队列', {exact:true})).toHaveCount(0)
  const cards=await panel.locator('.status-grid > *').all()
  const boxes=await Promise.all(cards.map(card=>card.boundingBox()))
  expect(boxes.every(box=>box && Math.abs(box.x-boxes[0]!.x)<1)).toBe(true)
  expect(boxes[1]!.y).toBeGreaterThanOrEqual(boxes[0]!.y+boxes[0]!.height)
  await expect(panel.getByText('备份', {exact:true})).toHaveCount(0)
  await expect(page.locator('.system-status summary i')).toHaveCount(1)
  await expect(panel.locator('i')).toHaveCount(0)
  await expect(panel.getByRole('button',{name:'刷新'})).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(panel).toBeHidden()
  await page.locator('[aria-label="打开系统状态"]').click()
  await page.getByRole('heading',{name:'我的文件'}).click()
  await expect(panel).toBeHidden()
})

test('未登录用户不能读取系统状态',async({request})=>{
  const response=await request.get('/api/system/status')
  expect(response.status()).toBe(401)
  const stream=await request.get('/api/system/status/stream')
  expect(stream.status()).toBe(401)
})
