import { expect, test } from '@playwright/test'
import { login } from './helpers'

test.use({viewport:{width:390,height:844},isMobile:true,hasTouch:true})

test('手机顶栏状态球和头像工具菜单交互',async({page})=>{
  await login(page)
  const statusTrigger=page.locator('.system-status summary')
  await expect(statusTrigger).toBeVisible()
  await statusTrigger.click()
  await expect(page.locator('.status-panel')).toBeVisible()
  await expect(page.locator('.status-panel').getByText('媒体会话')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('[aria-label="打开任务与工具菜单"]')).toHaveCount(0)
  await page.locator('[aria-label="打开账户与工具菜单"]').click()
  const menu=page.locator('.mobile-account-menu section')
  await expect(menu.getByText('任务中心')).toBeVisible()
  await expect(menu.getByText('系统状态')).toHaveCount(0)
  await expect(menu.getByText('回收站')).toBeVisible()
  await expect(menu.getByText('账户设置')).toBeVisible()
  await menu.getByRole('button',{name:/任务中心/}).click()
  const taskPanel=page.locator('.task-panel')
  await expect(taskPanel).toBeVisible()
  await expect(taskPanel).toHaveCSS('background-color','rgb(255, 255, 255)')
  await expect(page.locator('.file-grid')).toBeVisible()
  expect(await taskPanel.evaluate(panel=>{const rect=panel.getBoundingClientRect();const hit=document.elementFromPoint(rect.left+rect.width/2,rect.top+Math.min(rect.height/2,80));return hit===panel||panel.contains(hit)})).toBe(true)
  await page.keyboard.press('Escape')
  await page.locator('[aria-label="打开账户与工具菜单"]').click()
  await menu.getByRole('button',{name:/账户设置/}).click()
  await expect(menu).toBeHidden()
  await expect(page.locator('.account-modal')).toBeVisible()
  await expect(page.locator('.account-modal').getByRole('heading',{name:'账户设置'})).toBeVisible()
})
